### PR TITLE
Don't push rcfile into pylint if it is not present in file system

### LINKED ISSUE #251: linting requires rcfile
When a path to a pylintrc-file is specified, e.g. `%f\.pylintrc`, it will always expect that file to be present in the relative location, otherwise it will fail with 
`raise IOError("The config file {:s} doesn't exist!".format(config_file))`. 
But as I edit files outside of my default code folder where there is no rcfile, it might be useful to have a fallback-logic if the file is not present in that file's folder, something like 
```
Does this file exist? 
    Yes: Run pylint with it. 
    No:  Run pylint using default settings
```

### PR DESCRIPTION
**Pull request by Talon24**
Fixes #251
When a .rcfile is specified in the package options, this PR checks if the referenced file does actually exist.

That can be useful if you specified a relative path for the file, e.g. `%f\.pylintrc`, but don't have a seperate rcfile in every directory, allowing the user to do this:
> "If this program requires a unusual rcfile, I can add it there, but in any other case, just use my default setting"

### CODE REVIEW

File: lib/main.js [hunk 1]
```diff
@@ -138,7 +139,9 @@ export default {
           '--reports=n',
           '--output-format=text',
         ];
-        if (this.rcFile !== '') {
+        if (
+          this.rcFile !== '' &&
+          fs.existsSync(`${fixPathString(this.rcFile, fileDir, projectDir)}`)) {
```
Comment (Arcanemagus) [inline lib/main.js]: Please put the `) {` on the next line so it doesn't look like the next line is still part of the conditions.

Comment (Talon24) [reply lib/main.js]: Thanks, I added that
