### PR TITLE
Fix error whitelist

### LINKED ISSUE #236: linting fails when .pylintrc is present
I have a `.pylintrc` file that works just fine when I use the command line:

```
pylint example_script.py
Using config file /Users/dtenenba/dev/batch-demo/.pylintrc
************* Module example_script
W: 19, 0: FIXME do some logging here, print stack trace, etc (fixme)

------------------------------------------------------------------
Your code has been rated at 9.47/10 (previous run: 9.47/10, +0.00)
```

In Atom (linter-pylint 2.1.0)  things work fine if I do **not** have a .pylintrc file, but as long as I do, I get a dialog that pops up that says:

```
[Linter] Error running Pylint
See Console for more info. (Open View -> Developer -> Toggle Developer Tools)
```

This is what it says in the console:

```
Linter] Error running Pylint Error: Using config file /Users/dtenenba/dev/batch-demo/.pylintrc
    at Object.<anonymous> (main.js [sm]:134)
    at Generator.next (<anonymous>)
    at step (/Users/dtenenba/.atom/packages/linter-pylint/lib/main.js:7)
(anonymous) @ linter-registry.js [sm]:137
```

If I remove the .pylintrc file  everything works fine.
linter-pylint finds my .pylintrc whether it's in the current directory or my home directory, but I get the same behavior in both cases.

This happens regardless of the .pylintrc contents. In my case I generated the .pylintrc file with the command:

```
pylint --generate-rcfile > .pylintrc
```

...and did not modify it at all. I would like to, but only after this is resolved.

I'm working in a virtual environment (with pylint 1.8.1 installed in the virtualenv) and python 3.6.3, on macOS 10.12.6.

### PR DESCRIPTION
**Pull request by gucciferXCIV**
More information about what changes in [Pylint](https://github.com/PyCQA/pylint) caused the initial linter-pylint bug [here](https://github.com/AtomLinter/linter-pylint/issues/236#issuecomment-352263699).

Fixes #236

### CODE REVIEW

**Comment by gucciferXCIV** [comment]
@Arcanemagus Hey, can you do me a favor and look this over?

File: lib/main.js [hunk 1]
```diff
@@ -18,6 +18,7 @@ const os = lazyReq('os');
 // Some local variables
 const errorWhitelist = [
   /^No config file found, using default configuration$/,
+  /^Using config file .+$/,
```
Comment (ddaanet) [inline lib/main.js]: This would be simpler and just as correct:
`/^Using config file /,`

**Comment by ddaanet** [comment]
Oh, well! It seems I can merge the PR. Cool!

File: lib/main.js (hunk 1 above)
Comment (Arcanemagus) [reply lib/main.js]: You're technically right that since this list of RegEx is tested against every line of `stderr` either version would work (and yours is slightly better for performance). The merged version works when testing against the _entire_ `stderr` if the code is refactored later to do that, and matches the behavior of the existing RegEx though.

Comment (ddaanet) [reply lib/main.js]: I committed the simplification directly on master before your reply.

Speculative benefit in case we start matching the entire stderr does not seem worthwhile.

The behaviour of the existing regex is correct because we do match the entire line, but the new regex only matches the start of the line.

So I favored the simpler code. I'll revert my change if you care.

**Comment by Dundee** [comment]
Please release new version, this is major fix. Thanks!

**Comment by ddaanet** [comment]
@Arcanemagus sorry, I did not have the time and energy to figure out the release process. Life is keeping me quite busy...

**Comment by Dundee** [comment]
Could I help somehow?

**Comment by ddaanet** [comment]
@Dundee Slack ate the chat history… I think the relevant issue is this one: https://github.com/AtomLinter/Meta/issues/18

**Comment by Arcanemagus** [comment]
@AtomLinter/linter-pylint If there are no objections to the [Conventional Commits](http://conventionalcommits.org/) format being _required_ for all commits here, I can set up the automated release process described in https://github.com/AtomLinter/Meta/issues/18, meaning that as soon as commits are merged to `master` that would trigger a release it will happen automatically. See that issue for a bit more details.

For now I'll push out a release manually 😉.

**Comment by Arcanemagus** [comment]
Published in v2.1.1. 🎉

**Comment by ddaanet** [comment]
@Arcanemagus I am a bit wary of requiring Convential Commits format for all commits.

This will certainly create change requests during code review, that will produce rebase and force push, and tooling generally does not cope will with rebase. For one thing, github cannot show when the change was made, and it tends to create confusing code reviews (when comments are made on changes that appear later in the timeline after rebase).

I like the general idea of Conventional Commits, but the suggested implementation, based on squash, force-push and rebase is _terrible_. I would be happy with requiring conventional commit format only on master mainline commits (that is, PR merge commits).

All that being said, I would take automatic releases with conventional commits on all commits today over manual commits forever.

**Comment by Arcanemagus** [comment]
> the suggested implementation, based on squash, force-push and rebase is _terrible_.

I'm a bit confused where this is "suggested"? Part of adding this would be adding a pre-commit hook that lints the commit message, ensuring it follows the proper format. So the only people that would need to rebase _because of the commit message format_ would be people that explicitly disable that check (or failed to run `npm install` which means they probably also didn't lint their code, or test it...).

For example over in `atom-linter-pug` I've just been doing merge commits.

**Comment by Arcanemagus** [comment]
Ah, just searched through that Conventional Commits page, I just thought it outlined the format not suggested a workflow. It seems they wrote that assuming that messages would only be verified when doing the final merge, but that's far too error prone for my liking so I went with an automated setup that verifies _every_ message.

**Comment by ddaanet** [comment]
@Arcanemagus 
> Ah, just searched through that Conventional Commits page, I just thought it outlined the format not suggested a workflow. It seems they wrote that assuming that messages would only be verified when doing the final merge, but that's far too error prone for my liking so I went with an automated setup that verifies every message.

A pre-commit hook does make it more practical.

> Half the reason for doing a enforced style is it forces people to think about their commits and break them into isolated parts instead of bundling many different unrelated parts into a single commit.

For code review AND integration, it makes a lot more sense to aim for semantic granularity at the PR level.

* In my experience, code review tends to produce a lot of "coding style" and "cleanup" commits that are irrelevant for changelog and versioning. If the tooling makes this awkward, people will amend and rebase more. And that will break github code reviews.
* To keep diffs small enough for code review, a PR should not contain more than one semantic unit worthy of a changelog entry.
* Tools cannot force people to work in a certain way. That is what code review is for. 

Really, most of my issues against conventional commits on all commits come from git having no support for tracking history when rebasing. This is arguably a problem with git. But here we are…
